### ISSUE TITLE
Helm chart for Enrichment pipeline

### ISSUE THREAD

**Issue by ewill00** [Alvearie/health-patterns#11]
Need to determine how we adjust the Ingestion pipeline helm chart to also include Enrichment (both for deployment and for the NiFi flow)

This is just for helping with deployment of the Enrichment pipeline standalone - including DeID (but not ACD, let's leave that up to the user to configure their own)

**Comment by ibmatc** [comment]
There is now a Clinical Enrichment pipeline deployable independent of the Clinical Ingestion pipeline. It can be configured to automatically run based on FHIR server updates (FHIR-Trigger) or data can be fed into it directly.  See https://github.com/Alvearie/health-patterns/tree/main/helm-charts/health-patterns#clinical-enrichment
