### ISSUE TITLE
Error on helm dependency update

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#148]
I am following these directions:
https://github.com/Alvearie/health-patterns/blob/main/helm-charts/health-patterns/README_Helm.md

1. git clone https://github.com/Alvearie/health-patterns.git
2. cd health-patterns/helm-charts/health-patterns
3. helm dependency update

The helm dependency update fails with:
"Error: apiVersion 'v2' is not valid. The value must be "v1""

**Comment by ibmatc** [comment]
Discussed with Roger - he was using the wrong helm version. Closing.
