### ISSUE TITLE
NiFi HTTP Post URL responds with 503

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#151]
I have a deployment in the test-ingestion namespace in the health-patterns-1 cluster.

NAME: ingestion
LAST DEPLOYED: Thu Jun 17 13:10:35 2021
NAMESPACE: test-ingestion
STATUS: deployed
REVISION: 1
NOTES:
Welcome to the

       d8888 888                                    d8b
      d88888 888                                    Y8P
     d88P888 888
    d88P 888 888 888  888  .d88b.   8888b.  888d888 888  .d88b.
   d88P  888 888 888  888 d8P  Y8b     "88b 888P"   888 d8P  Y8b
  d88P   888 888 Y88  88P 88888888 .d888888 888     888 88888888
 d8888888888 888  Y8bd8P  Y8b.     888  888 888     888 Y8b.
d88P     888 888   Y88P    "Y8888  "Y888888 888     888  "Y8888

                               Clinical Data Ingestion Framework

Pattern: Clinical Ingestion

The following services have been deployed:
- Primary FHIR Server --------- https://test-ingestion-ingestion-fhir.wh-health-patterns.dev.watson-health.ibm.com/fhir-server/api/v4
- NiFi Server ----------------- https://test-ingestion-ingestion-nifi.wh-health-patterns.dev.watson-health.ibm.com/nifi
- NiFi HTTP Post API ---------- https://test-ingestion-ingestion-nifi-http-post.wh-health-patterns.dev.watson-health.ibm.com
- NiFi Registry --------------- https://test-ingestion-ingestion-nifi-registry.wh-health-patterns.dev.watson-health.ibm.com/nifi-registry
- Zookeeper
- Kafka

Access to the Kafka server is handled via load balancer. It may take a few minutes for the load balancer IP to be available.

Watch the status of the kafka service by running the following command and wait until the external IP address appears:

  kubectl get --namespace test-ingestion svc -w | grep kafka-0-external

Once the external IP has been assigned run the following command to identify the kafka server broker:

  export KAFKA_IP=$(kubectl get svc --namespace test-ingestion ingestion-kafka-0-external -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
  export KAFKA_PORT=$(kubectl get svc ingestion-kafka-0-external -o jsonpath='{.spec.ports[0].port}')
  echo Kafka Broker: $KAFKA_IP:$KAFKA_PORT

Inside the cluster you can access the services at the following locations:
- Primary FHIR Server: ingestion-fhir.test-ingestion.svc.
- NiFi Server: ingestion-nifi.test-ingestion.svc.
- NiFi Registry: ingestion-nifi-registry.test-ingestion.svc.
- Kafka: ingestion-kafka.test-ingestion.svc.
- Zookeeper: ingestion-zookeeper.test-ingestion.svc.

My NIFI "healthcheck" (nifi-api/flow/process-groups/root) works, but any submission to the Nifi HTTP Post URL returns a HTTP 503 error.

**Comment by ibmatc** [comment]
The issue was that the release name was being used to target the nifi service, but the nifi service was being named with a hard-coded "alvearie" due to complications in the nifi helm chart.  We can revisit in future updates to use of that chart, but for now hard-coding to alvearie-nifi is sufficient
