### ISSUE TITLE
Incorrect directory listed in /helm-charts/fhir README

### ISSUE THREAD

**Issue by KathrynElrod** [Alvearie/health-patterns#167]
In `/helm-charts/fhir/README.md`, in section `Installation:Checkout the Code`, the line `cd health-patterns/clinical-ingestion/helm-charts/alvearie-ingestion/charts/fhir` should be `cd health-patterns/clinical-ingestion/helm-charts/fhir`.

**Comment by ranum** [comment]
Closing this as it is no longer valid since we are now using the alvearie-helm helm chart (there is no fhir chart within health patterns)
