### ISSUE TITLE
NLP_Insights Configuration API - HTTP 500 error returned when HTTP 400 should be returned

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#227]
Activating an nlp-insights configuration that does not exist results in an HTTP 400 error. 

Deleting an nlp-insights configuration that does not exist results in an HTTP 500 Error but should be HTTP 400.

**Comment by ranum** [comment]
This is now fixed with the recent changes to nlp-insights service.

![Screen Shot 2021-09-07 at 1 39 27 PM](https://user-images.githubusercontent.com/1405480/132394832-48c8d188-3a65-426e-963f-0058906ca9da.png)
