### ISSUE TITLE
NLP-Insights - ACD API Key is exposed when using /config/{config name} 

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#256]
I created an acd config during deploy and then recalled it via /config/{config name} and the ACD API Key is displayed in the response:

{"name": "acd", "nlpServiceType": "acd", "config": {"endpoint": "https://us-east.wh-acd.cloud.ibm.com/wh-acd/api", "apikey": "**9GSFDhHUrn03zCJZILz_ZmG7YqcjsXCOpppaqiejQqjd**", "flow": "wh_acd.ibm_clinical_insights_v1.0_standard_flow"}}

Not a big concern at the moment, but I wrote this issue to document the situation.

**Comment by ranum** [comment]
fixed, apikey is now masked
