### ISSUE TITLE
Ingest/Enrich to have a synchronous response option in addition to async

### ISSUE THREAD

**Issue by ewill00** [Alvearie/health-patterns#261]
Currently the Ingest and Enrich pattern provide an asynchronous pattern for sending patient data to/through them.  

Create an alternative pattern that will wait until the data is successfully through the pipeline or fails, at which time the interface would respond

**Comment by ibmatc** [comment]
Fixed: https://github.com/Alvearie/health-patterns/commit/ad24db33d228f592488811f460906e6b835d6e32
