### ISSUE TITLE
Need better startup logging in exposekafka.py

### ISSUE THREAD

**Issue by brendan-bull** [Alvearie/health-patterns#291]
When we tried to install the ingestion pattern onto OpenShift, there were a variety of issues that boiled down to OpenShift not allowing us to run as user 1001 by default.  While debugging that, one of the things we noticed was that the expose kafka pod didn't start and didn't give us any useful information as to why.

After a bit of exploration, we discovered that the startup logic was eating the connection exceptions.  Once we instrumented it to print the exception, we realized what the root problem was and found that the other pod wasn't starting because the enrich-kafka user didn't have `anyuid` SCC granted.

Here's a proposed fix that will print a message (with the corresponding exception) every 60 seconds.  It'll sleep for 5 seconds so we don't burn through the connection loop quite as furiously.

```
import time
import logging

...

app.logger.setLevel(logging.INFO)
app.logger.info("Attempting to connect to Kafka server")
last_recorded_time = round(time.time() * 1000)
while True:
    try:
        KafkaConsumer(bootstrap_servers=kafkabootstrap,
                                 sasl_mechanism="PLAIN", sasl_plain_username=kafkauser, sasl_plain_password=kafkapw)
        break
    except Exception as e:
        current_time = round(time.time() * 1000)
        # If the Kafka server isn't up for any reason, we'll print a message every minute until it comes up.
        if current_time - last_recorded_time > 60 * 1000:
            app.logger.error(f"Unable to connect Kafka server: {e}")
            app.logger.info("Retrying connection to Kafka server...")
            last_recorded_time = current_time
        # Even though we only print a message every 60 seconds, we'll try to connect every 5 seconds
        # to minimize container startup time.
        time.sleep(5)

# kafka is now up and running
app.logger.info("Connected to Kafka server")
```

**Comment by ranum** [comment]
Done
