### ISSUE TITLE
expose-kafka service needs a kubernetes readiness probe

### ISSUE THREAD

**Issue by brendan-bull** [Alvearie/health-patterns#293]
This issue is related to https://github.com/Alvearie/health-patterns/issues/291.

When debugging startup issues that were ultimately due to user permission on OpenShift, one of the other things that made debug challenging was that the pod was reporting that it was healthy despite the fact that it was spinning its wheels in the startup loop unable to talk to the Kafka server.

It might be worth adding a `readinessProbe` section to the deployment yaml for this and any other services that don't have one.  In this case, perhaps we could just set a status in temp file indicating "not ready"until exposekafka.py successfully loads all of its topics.

**Comment by ranum** [comment]
Done
