### ISSUE TITLE
expose-kafka: incorrect error returned for invalid FHIR data

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#319]
I have 2 patient bundles with different types of invalid FHIR Data:
github.com/Alvearie/health-patterns/blob/main/ingest/src/test/resources/Patients/Salina386_Buckridge80_Invalid_Bundle.json
github.com/Alvearie/health-patterns/blob/main/ingest/src/test/resources/Patients/Salina386_Buckridge80_Invalid_Data.json

When I submit these specifying the expose-kafka response and failure topics, I get the following response:
  _**"status" : 520,**_
  "headers" : {
    "Date" : [ "Wed, 17 Nov 2021 19:30:21 GMT" ],
    "Set-Cookie" : [ "__cflb=02DiuDr9xiksdProDcfh1ABA1f6KZKPZRqYP3gaVbjYfW; SameSite=None; Secure; path=/; expires=Thu, 18-Nov-21 18:30:21 GMT; HttpOnly" ],
    "Server" : [ "cloudflare" ],
    "Transfer-Encoding" : [ "chunked" ],
    "CF-RAY" : [ "6afb5e4b498a2b1c-ORD" ],
    "Content-Type" : [ "text/html" ],
    "Connection" : [ "keep-alive" ],
    "CF-Cache-Status" : [ "DYNAMIC" ],
    "Cache-Control" : [ "no-store, no-cache" ],
    "Expect-CT" : [ "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"" ]
  },
  _**"rawBody" : "<html>\r\n<head><title>520 Origin Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>520 Origin Error</h1></center>\r\n<hr><center>cloudflare-nginx</center>\r\n</body>\r\n</html>\r\n"**_
}

I was expecting a response that contained an some indication of the error relating to the invalid FHIR data.
I was also expecting a different response code although not entirely sure what it should be.

**Comment by rguderian** [comment]
I have ingestion deployed in namespace test-ingestion if you'd like to use it for investigation.

**Comment by ibmatc** [comment]
In the logs for this error I noticed that the request coming in to expose-kafka has a malformed attribute set:

/?topic=?topic=?topic=ingest.topic.in&response_topic=ingest.topic.out&failure_topic=ingest.topic.failure

the addition of extra "?topic=" strings is causing this issue.  This needs to be fixed in the caller, not in expose-kafka.
