### ISSUE TITLE
Unable to Delete the Last NLP-Insights Configuration

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#364]
Test: enrich_NLP_Insights_Config_CRUD   

The test steps:
1. Create an NLP configuration named "NLP-PUT-config"
2. Get config info for "NLP-PUT-config"
3. Get all configs and verify "NLP-PUT-config" in the list
4. Set "NLP-PUT-config" as the default config
5. Get the default config and verify it is "NLP-PUT-config"
6. Update "NLP-PUT-config"when it is the default
7. Attempt to delete "NLP-PUT-config" while it is the default config (verify http 400 response)
8. Clear the default configuration
9. Delete "NLP-PUT-config" & verify success (http 200 response)
10. Get all configs and verify"NLP-PUT-config" not in the list
11. Delete "NLP-PUT-config" and verify response (http 400)

This was a successful test sequence using the old version of nlp-insights.

With the new version of nlp-insights, the test sequence fails at the delete in step 9.  

This sequence of steps will work on the new version of nlp-insights when multiple configurations exist.   This sequence fails when the configuration we are testing with is the last existing configuration.

**Comment by ntl-ibm** [comment]
I don't see this error. Please include the message in the 400 response code.

**Comment by rguderian** [comment]
Sorry, I should have included the error message:
<title>400 Bad Request</title>\n<h1>Bad Request</h1>\n<p>fNLP-PUT-config has an existing override and cannot be deleted</p>

**Comment by ntl-ibm** [comment]
The message implies you have an override that uses that config.

I do not think clearing the default will remove the overrides. There is a different DELETE /config/resource API call for that....

You do not have any overrides being set in your recreate, so perhaps you have some other process involved that is not listed here.

**Comment by rguderian** [comment]
Yes Nick, you are correct.   The configuration I was trying to delete had an override set from another test.   Once I cleaned up both tests, all tests were successful.
