### ISSUE TITLE
Move DeID docker file & helm charts to DeID project

### ISSUE THREAD

**Issue by ewill00** [Alvearie/health-patterns#43]
Still want to reference it from our overall Ingestion helm chart, but the artifacts should be moved to DeID

**Comment by luisgarcc** [comment]
The code has been copied to the de-id project here https://github.com/Alvearie/de-identification/pull/32
We still have it in our repository due to the `ct lint` problem (https://github.com/Alvearie/health-patterns/issues/54), which we'll have to eventually figure out.
