### ISSUE TITLE
Minor README.md change to reflect HL7 support

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#50]
https://github.com/Alvearie/health-patterns/blob/main/clinical-ingestion/README.md

Current Statement:
"Currently, the only supported medical data format is FHIR bundles. Other formats are on our backlog and will be coming soon, including HL7 and DICOM image data."

It appears that HL7 is now supported in some fashion, and the above statement should refect that support.

**Comment by ibmatc** [comment]
I updated the documentation to reflect the current supported formats
