### ISSUE TITLE
Minor Issues in the setup/deploy instructions

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#55]
https://github.com/Alvearie/health-patterns/tree/main/clinical-ingestion/helm-charts/alvearie-ingestion
cd clinical-ingestion/helm-charts/alvearie-ingestion
should be
cd health-patterns/clinical-ingestion/helm-charts/alvearie-ingestion

https://github.com/Alvearie/health-patterns/tree/main/clinical-ingestion/helm-charts/alvearie-ingestion/charts/fhir#installation
cd clinical-ingestion/helm-charts/fhir
should be 
cd health-patterns/clinical-ingestion/helm-charts/fhir

https://github.com/Alvearie/health-patterns/tree/main/clinical-ingestion/helm-charts/alvearie-ingestion/charts/fhir#using-the-chart
kubectl exec <pod-id> -c fhir-server -- cat server.xml | grep -A2 BasicRealm
should be
kubectl exec <pod-id> -c server -- cat server.xml | grep -A2 BasicRealm

https://github.com/Alvearie/health-patterns/tree/main/clinical-ingestion/helm-charts/alvearie-ingestion/charts/deid#installation
cd clinical-ingestion/helm-charts/deid
should be 
cd health-patterns/clinical-ingestion/helm-charts/deid

https://github.com/Alvearie/health-patterns/tree/main/clinical-ingestion/helm-charts/alvearie-ingestion/charts/nifi-registry#installation
cd clinical-ingestion/helm-charts/nifi-registry
should be
cd health-patterns/clinical-ingestion/helm-charts/nifi-registry

**Comment by ibmatc** [comment]
I have updated the kubectl command to reflect the renaming of "fhir-server" to "server".  

The other concerns I don't believe should be updated.  It is standard practice to assume you are already in the project the documentation is referring to (health-patterns) and all paths are relative to that.
