### ISSUE TITLE
Clarify use of the FHIR_LISTEN_PORT

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#58]
https://github.com/Alvearie/health-patterns/tree/main/clinical-ingestion#running-a-fhir-bundle-through-the-clinical-ingestion-flow

More explanation is needed on the FHIR_LISTEN_PORT parameter.     My first reading of this section did not give me much insight into what the FHIR_LISTEN_PORT was or where to find it value.   

I had to ask David Ranum what this parameter was for and how to find it.

**Comment by ibmatc** [comment]
Fixed.
