### ISSUE TITLE
Generate a request ID for the Clinical Ingestion REST API flow

### ISSUE THREAD

**Issue by ewill00** [Alvearie/health-patterns#67]
Ingesting a patient through the REST API does not offer a way to match it against an either success or failed response.  Some of this exists within the NiFi flow but only if you get that deep into it - need something higher level

Example: Post 10 patients through REST API if any of those patients fail, there is no way to match a failure to the REST API request.

**Comment by luisgarcc** [comment]
Fix delivered to the ingestion NiFi flow. Documentation udpated.
