### ISSUE TITLE
FHIR resources getting stuck in Push to FHIR Flow

### ISSUE THREAD

**Issue by luisgarcc** [Alvearie/health-patterns#78]
There is a processor in the *Save to FHIR* process group. type *InvokeScriptedProcessor* that loaded with a Warning out of the box.
The FHIR resources get stuck in that processor. 

The workaround is to copy and reconnect the processor.

We should add this to a known issues section.

**Comment by ibmatc** [comment]
This was resolved with a recent update to the Clinical Ingestion Nifi flow: https://github.com/Alvearie/health-patterns-nifi-flows/commit/9211c9cbf8ccd7588722ce0da6c61e25109b2293
