### ISSUE TITLE
FHIR resources need to have a UUID

### ISSUE THREAD

**Issue by luisgarcc** [Alvearie/health-patterns#79]
Pushing a perfectly valid FHIR resource out of Synthea causes problems with the framework because it expects a UUID in its `id` field.

The purpose of this issue is to document that pre-requisite, or add that to a known issues section (with the workaround ${UUID}) but hopefully to remove that requirement and add the UUID inside the framework if needed.

**Comment by ibmatc** [comment]
This was fixed in the nifi flow under: https://github.com/Alvearie/health-patterns-nifi-flows/commit/c4aa27190a7d6f2ac44bcb924a989996e06361e2
