### ISSUE TITLE
Make the "Push to FHIR" part of the DeIdentify Custom Processor optional

### ISSUE THREAD

**Issue by luisgarcc** [Alvearie/health-patterns#80]
The purpose of this task is to make the Push Deidentified resource to FHIR optional via configuration in the DeIdentify NiFi Custom Processor. There could be a boolean checkmark that indicates whether to do that or not, when the checkmark is unselected the validation for the FHIR server would be skipped.

**Comment by ibmatc** [comment]
The use of a Nifi Custom Processor for the Healh Patterns Deid wrapper has been migrated over to "deid-prep", a service that provides the same function but can be deployed independent of Nifi.  With this migration, support was added to allow toggling whether the request will get stored in a target FHIR server or not, effectively resolving this issue.
