### ISSUE TITLE
Document Ingress support for AWS & Azure

### ISSUE THREAD

**Issue by ibmatc** [Alvearie/health-patterns#91]
Ingress support described for the Clinical Ingestion pipeline was developed using IBM Cloud.  Currently the instructions do not address similar support for the other primary cloud environments.  Ingress should be portable across clouds, but there are nuances between each environment that require additional steps to enable.  Please investigate each and document (or automate if possible) the steps required to use the Ingress support for AWS, Azure, and GCP.

**Comment by ewill00** [comment]
Closed with #87
